name: projetowell
description: Aplicativo de monitoramento de dados vitais.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  animate_do: ^3.2.0
  mask_text_input_formatter: ^2.5.0
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.8.0
  http: ^1.2.0
  uuid: ^4.0.0
  google_fonts: ^6.2.0
  fl_chart: ^0.70.0
  table_calendar: ^3.1.3
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/heart.json  # Registrando animações Lottie
    - assets/lottie/activity.json
    - assets/lottie/weigth.json
    - assets/lottie/nutrition.json
    - assets/lottie/doctor.json
    - assets/lottie/agenda.json
    - assets/lottie/diabetes.json
    - assets/lottie/heartrate.json
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  # Definindo o ícone do aplicativo
